- name: install
  apt:
    name: redis-server

- name: configure redis.conf
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
  register: configuration

- name: restart redis
  systemd:
    name: redis
    state: restarted
  when: configuration.changed
