- name: install
  apt:
    name: memcached

- name: configure memcached.conf
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
  register: configuration

- name: restart memcached
  systemd:
    name: memcached
    state: restarted
  when: configuration.changed

