- name: add apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: add repository
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main'

- name: install
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - postgresql-11
      - python-psycopg2
      - libpq-dev

- name: configure postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/11/main/postgresql.conf
  notify:
    - restart postgresql-11

- name: wait for postgresql
  wait_for:
    port: "{{ postgresql.config.port }}"

- name: change default user to {{ postgresql.username }} / {{ postgresql.password }}
  postgresql_user:
    name: "{{ postgresql.username }}"
    password: "{{ postgresql.password }}"
    role_attr_flags: SUPERUSER
  become_user: postgres
  when: postgresql.password != ''

- name: change default user to {{ postgresql.username }}
  postgresql_user:
    name: "{{ postgresql.username }}"
    role_attr_flags: SUPERUSER
  become_user: postgres
  when: postgresql.password == ''

- name: copy .pgpass for postgres
  template:
    src: user-pgpass.j2
    dest: /var/lib/postgresql/.pgpass
    owner: postgres
    group: postgres
    mode: 0600
