- name: install
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - postfix
      - postfix-pcre

- name: configure main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  register: configuration

- name: configure virtual.map.pcre
  template:
    src: virtual.map.pcre.j2
    dest: /etc/postfix/virtual.map.pcre
  register: virtualmap

- name: restart postfix
  systemd:
    name: postfix
    state: restarted
  when: configuration.changed or virtualmap.changed
