- name: copy .bashrc for user vagrant
  template:
    src=bashrc.j2
    dest=/home/vagrant/.bashrc
    owner=vagrant
    group=vagrant

- name: copy .bashrc for user root
  template:
    src=bashrc.j2
    dest=/root/.bashrc
    owner=root
    group=root
