- name: install
  apt:
    name: "clamav-daemon"

- name: download main.cvd
  get_url:
    url: http://db.local.clamav.net/main.cvd
    dest: /var/lib/clamav/main.cvd
    mode: 0755
  notify:
    - restart clamav-daemon

- name: download daily.cvd
  get_url:
    url: http://db.local.clamav.net/daily.cvd
    dest: /var/lib/clamav/daily.cvd
    mode: 0755
  notify:
    - restart clamav-daemon

- name: download main.cvd
  get_url:
    url: http://db.local.clamav.net/bytecode.cvd
    dest: /var/lib/clamav/bytecode.cvd
    mode: 0755
  notify:
    - restart clamav-daemon

- name: update config
  template:
    src: clamd.conf.j2
    dest: /etc/clamav/clamd.conf
  notify:
    - restart clamav-daemon
