---
- name: add key
  apt_key: keyserver=keyserver.ubuntu.com id=0C49F3730359A14518585931BC711F9BA15703C6 state=present

- name: app repository
  apt_repository: repo='deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse' state=present

- name: install
  apt: name={{ item }} state=present
  with_items:
    - mongodb-org
    - python-pymongo
  register: mongoinstall

- name: force mongodb start, if installed
  service: name=mongod state=started
  when: mongoinstall.changed

- name: wait for mongodb, if installed
  wait_for: port=27017
  when: mongoinstall.changed

- name: add vagrant user
  mongodb_user: user=vagrant password=vagrant database=admin roles=userAdminAnyDatabase
  when: mongoinstall.changed

- name: configure mongod.conf
  template:
    src=mongod.conf.j2
    dest=/etc/mongod.conf
  notify:
    - restart mongodb
  register: mongodbconfig

- name: force mongodb restart, if config changed
  service: name=mongod state=restarted
  when: mongodbconfig.changed

- name: wait for mongodb, if config changed
  wait_for: port={{mongodb.config.net.port}}
  when: mongodbconfig.changed

- name: change user to {{ mongodb.username }} / {{ mongodb.password }}
  mongodb_user:
    user={{ mongodb.username }}
    password={{ mongodb.password }}
    database=admin
    login_database=admin
    login_user=vagrant
    login_password=vagrant
    roles=userAdminAnyDatabase

- name: copy .mongorc.js file for user root
  template:
    src=user-mongorc.js.j2
    dest=/root/.mongorc.js
    owner=root
    group=root
    mode=0600

- name: copy .mongorc.js for user vagrant
  template:
    src=user-mongorc.js.j2
    dest=/home/vagrant/.mongorc.js
    owner=vagrant
    group=vagrant
    mode=0600
