---
- name: add key
  apt_key: url=https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc state=present

- name: app repository
  apt_repository: repo='deb https://dl.bintray.com/rabbitmq/debian xenial main erlang' state=present

- name: apt | upgrade
  apt: update_cache=yes

- name: install
  apt: name={{ item }} state=present
  with_items:
    - rabbitmq-server

- name: install plugins
  rabbitmq_plugin: names={{ item }} state=enabled
  with_items:
    - rabbitmq_management
  notify:
  - restart rabbitmq-server

- name: configure rabbitmq
  template:
    src=rabbitmq.conf.j2
    dest=/etc/rabbitmq/rabbitmq.conf
  notify:
  - restart rabbitmq-server

- name: add user admin
  rabbitmq_user: user={{ rabbitmq.username }} password={{ rabbitmq.password }} configure_priv=.* read_priv=.* write_priv=.* tags=administrator state=present
  notify:
  - restart rabbitmq-server

- name: remove user guest
  rabbitmq_user: user=guest state=absent
  notify:
  - restart rabbitmq-server
