- name: install
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - php7.2
      - php7.2-common
      - php7.2-cli
      - php-apcu
      - php-ast
      - php-xdebug

- name: install fpm
  apt:
    name: "php7.2-fpm"
  when: role.nginx

- name: install modules
  apt:
    name: "{{ php.modules }}"

- name: install memcached
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - php-memcache
      - php-memcached
  notify:
    - restart php7.2-original-fpm
  when: role.memcached

- name: install mariadb
  apt:
    name: php7.2-mysql
  notify:
    - restart php7.2-original-fpm
  when: role.mariadb

- name: install postgresql
  apt:
    name: php7.2-pgsql
  notify:
    - restart php7.2-original-fpm
  when: role.postgresql

- name: install blackfire-probe
  apt:
    name: blackfire-php
  notify:
    - restart php7.2-original-fpm
  when: role.blackfire

- name: configure cli php.ini
  template:
    src: cli.php.ini.j2
    dest: /etc/php/7.2/cli/php.ini
  notify:
    - restart php7.2-original-fpm

- name: configure fpm php.ini
  template:
    src: fpm.php.ini.j2
    dest: /etc/php/7.2/fpm/php.ini
  notify:
    - restart php7.2-original-fpm
  when: role.nginx

- name: configure php-fpm
  template:
    src: php-fpm.conf.j2
    dest: /etc/php/7.2/fpm/php-fpm.conf
  notify:
    - restart php7.2-original-fpm
  when: role.nginx

- name: create .composer for user vagrant
  file:
    path: /home/vagrant/.composer
    state: directory
    owner: vagrant
    group: vagrant

- name: copy .composer/composer.json for user vagrant
  template:
    src: composer.json.j2
    dest: /home/vagrant/.composer/composer.json

- name: download composer
  get_url:
    url: https://github.com/composer/composer/releases/download/1.7.3/composer.phar
    dest: /usr/local/bin/composer
    mode: 0755

- name: composer global update for user vagrant
  command: /usr/local/bin/composer global update
  become_user: vagrant
