---
- name: change sysctl memory allocation
  sysctl: name=vm.max_map_count value=262144 state=present

- name: add apt key
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

- name: app repository
  apt_repository: repo='deb https://artifacts.elastic.co/packages/5.x/apt stable main' state=present

- name: install
  apt: name={{ item }} state=present
  with_items:
    - elasticsearch
    - kibana
    - openjdk-8-jre-headless

#- name: link elasticsearch rc0.d
#  file:
#    src=/etc/init.d/elasticsearch
#    dest=/etc/rc0.d/K01elasticsearch
#    state=link
#
#- name: link elasticsearch rc1.d
#  file:
#    src=/etc/init.d/elasticsearch
#    dest=/etc/rc1.d/K01elasticsearch
#    state=link
#
#- name: link elasticsearch rc2.d
#  file:
#    src=/etc/init.d/elasticsearch
#    dest=/etc/rc2.d/S01elasticsearch
#    state=link
#
#- name: link elasticsearch rc3.d
#  file:
#    src=/etc/init.d/elasticsearch
#    dest=/etc/rc3.d/S01elasticsearch
#    state=link
#
#- name: link elasticsearch rc4.d
#  file:
#    src=/etc/init.d/elasticsearch
#    dest=/etc/rc4.d/S01elasticsearch
#    state=link
#
#- name: link elasticsearch rc5.d
#  file:
#    src=/etc/init.d/elasticsearch
#    dest=/etc/rc5.d/S01elasticsearch
#    state=link
#
#- name: link elasticsearch rc6.d
#  file:
#    src=/etc/init.d/elasticsearch
#    dest=/etc/rc6.d/K01elasticsearch
#    state=link

- name: fix -Xms
  lineinfile:
    dest=/etc/elasticsearch/jvm.options
    line='-Xms128m'
    regexp='^-Xms'
    state=present
  notify:
      - restart elasticsearch

- name: fix -Xmx
  lineinfile:
    dest=/etc/elasticsearch/jvm.options
    line='-Xmx128m'
    regexp='^-Xmx'
    state=present
  notify:
      - restart elasticsearch

- name: configure elasticsearch.yml
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
  notify:
      - restart elasticsearch

- name: configure kibana.yml
  template:
    src=kibana.yml.j2
    dest=/etc/kibana/kibana.yml
  notify:
      - restart kibana

- name: uninstall all modules (there is no update support)
  command: "{{ elasticsearch.config['path.home'] }}/bin/elasticsearch-plugin remove {{ item }}"
  with_items: "{{ elasticsearch.plugins }}"

- name: install all modules
  command: "{{ elasticsearch.config['path.home'] }}/bin/elasticsearch-plugin install {{ item }}"
  with_items: "{{ elasticsearch.plugins }}"
