- name: add key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 4F4EA0AAE5267A6C

- name: add repository
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main'

- name: install
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - php7.3
      - php7.3-common
      - php7.3-cli
      - php7.3-fpm
      - php-apcu
      - php-ast
      - php-xdebug

- name: install modules
  apt:
    name: "{{ php.modules }}"

- name: install memcached
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - php-memcache
      - php-memcached
  notify:
    - restart php7.3-fpm
  when: role.memcached

- name: install mariadb
  apt:
    name: php7.3-mysql
  notify:
    - restart php7.3-fpm
  when: role.mariadb

- name: install postgresql
  apt:
    name: php7.3-pgsql
  notify:
    - restart php7.3-fpm
  when: role.postgresql

- name: install blackfire-probe
  apt:
    name: blackfire-php
  notify:
    - restart php7.3-fpm
  when: role.blackfire

- name: configure cli php.ini
  template:
    src: cli.php.ini.j2
    dest: /etc/php/7.3/cli/php.ini
  notify:
    - restart php7.3-fpm

- name: configure fpm php.ini
  template:
    src: fpm.php.ini.j2
    dest: /etc/php/7.3/fpm/php.ini
  notify:
    - restart php7.3-fpm

- name: configure php-fpm
  template:
    src: php-fpm.conf.j2
    dest: /etc/php/7.3/fpm/php-fpm.conf
  notify:
    - restart php7.3-fpm

- name: create .composer for user vagrant
  file:
    path: /home/vagrant/.composer
    state: directory
    owner: vagrant
    group: vagrant

- name: copy .composer/composer.json for user vagrant
  template:
    src: composer.json.j2
    dest: /home/vagrant/.composer/composer.json

- name: download composer
  get_url:
    url: https://github.com/composer/composer/releases/download/1.7.3/composer.phar
    dest: /usr/local/bin/composer
    mode: 0755

- name: composer global update for user vagrant
  command: /usr/local/bin/composer global update
  become_user: vagrant
