---
- name: install
  apt: name={{ item }} state=present
  with_items:
    - postgresql-9.5
    - python-psycopg2

- name: configure postgresql.conf
  template:
    src=postgresql.conf.j2
    dest=/etc/postgresql/9.5/main/postgresql.conf
  notify:
      - restart postgresql

- name: wait for postgresql
  wait_for: port={{postgresql.config.port}}

- name: change default user to {{ postgresql.username }} / {{ postgresql.password }}
  become_user: postgres
  postgresql_user: name={{ postgresql.username }} password={{ postgresql.password }} role_attr_flags=SUPERUSER

- name: copy .pgpass for postgres
  template:
    src=user-pgpass.j2
    dest=/var/lib/postgresql/.pgpass
    owner=postgres
    group=postgres
    mode=0600
