- name: install
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - postgresql-10
      - python-psycopg2
      - libpq-dev

- name: configure postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/10/main/postgresql.conf
  notify:
    - restart postgresql-10-original

- name: wait for postgresql
  wait_for:
    port: "{{ postgresql.config.port }}"

- name: change default user to {{ postgresql.username }} / {{ postgresql.password }}
  postgresql_user:
    name: "{{ postgresql.username }}"
    password: "{{ postgresql.password }}"
    role_attr_flags: SUPERUSER
  become_user: postgres
  when: postgresql.password != ''

- name: change default user to {{ postgresql.username }}
  postgresql_user:
    name: "{{ postgresql.username }}"
    role_attr_flags: SUPERUSER
  become_user: postgres
  when: postgresql.password == ''

- name: copy .pgpass for postgres
  template:
    src: user-pgpass.j2
    dest: /var/lib/postgresql/.pgpass
    owner: postgres
    group: postgres
    mode: 0600
