- name: add key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: F1656F24C74CD1D8

- name: add repository
  apt_repository:
    repo: 'deb [arch=amd64] http://mirror.netcologne.de/mariadb/repo/10.1/ubuntu bionic main'

- name: install
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - mariadb-server-10.1
      - mariadb-client-10.1
      - python-pymysql

- name: configure mysql
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify:
    - restart mariadb-10.1

- name: wait for mariadb
  wait_for:
    port: "{{ mariadb.config.mysqld.port }}"

- name: set plugin '' on root user
  command: mysql -e "UPDATE mysql.user SET plugin='' WHERE user='root'; FLUSH PRIVILEGES;"
  ignore_errors: yes

- name: change default user to {{ mariadb.username }} / {{ mariadb.password }}
  mysql_user:
    name: "{{ mariadb.username }}"
    password: "{{ mariadb.password }}"
    host: localhost
    login_unix_socket: "{{ mariadb.config.mysqld.socket }}"
  when: mariadb.password != ''

- name: change default user to {{ mariadb.username }}
  mysql_user:
    name: "{{ mariadb.username }}"
    host: localhost
    login_unix_socket: "{{ mariadb.config.mysqld.socket }}"
  when: mariadb.password == ''

- name: copy .my.cnf file for user root
  template:
    src: user-my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: copy .my.cnf for user vagrant
  template:
    src: user-my.cnf.j2
    dest: /home/vagrant/.my.cnf
    owner: vagrant
    group: vagrant
    mode: 0600
