---
- name: add key
  apt_key: keyserver=keyserver.ubuntu.com id=4F4EA0AAE5267A6C state=present

- name: app repository
  apt_repository: repo='deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main' state=present

- name: app src repository
  apt_repository: repo='deb-src http://ppa.launchpad.net/ondrej/php/ubuntu xenial main' state=present

- name: install core, common, cli, fpm
  apt: name={{ item }} state=present
  with_items:
    - php7.2
    - php7.2-common
    - php7.2-cli
    - php7.2-fpm
    - php-apcu
  notify:
    - restart php7.2-fpm

- name: install memcached
  apt: name={{ item }} state=present
  with_items:
    - php7.2-memcached
  notify:
    - restart php7.2-fpm
  when: role.memcached

- name: install mongodb
  apt: name={{ item }} state=present
  with_items:
    - php7.2-mongodb
  notify:
    - restart php7.2-fpm
  when: role.mongodb

- name: install mysql
  apt: name={{ item }} state=present
  with_items:
    - php7.2-mysql
  notify:
    - restart php7.2-fpm
  when: role.mariadb

- name: install pgsql
  apt: name={{ item }} state=present
  with_items:
    - php7.2-pgsql
  notify:
    - restart php7.2-fpm
  when: role.postgresql

- name: install redis
  apt: name={{ item }} state=present
  with_items:
    - php7.2-redis
  notify:
    - restart php7.2-fpm
  when: role.redis

- name: install sybase
  apt: name={{ item }} state=present
  with_items:
    - php7.2-sybase
  notify:
    - restart php7.2-fpm
  when: role.freetds

# todo use the real packages when available
- name: install modules
  apt: name="{{ item }}" state=present
  with_items:
    - php7.2-curl
    - php7.2-gd
    - php7.2-imagick
    - php7.2-intl
    - php7.2-mbstring
    #- php7.2-mcrypt
    - php7.2-sqlite3
    #- php7.2-xdebug
    - php7.2-xml
  notify:
    - restart php7.2-fpm

- name: configure cli php.ini
  template:
    src=cli.php.ini.j2
    dest=/etc/php/7.2/cli/php.ini

- name: configure fpm php.ini
  template:
    src=fpm.php.ini.j2
    dest=/etc/php/7.2/fpm/php.ini
  notify:
    - restart php7.2-fpm

- name: fpm config
  template:
    src=php-fpm.conf.j2
    dest=/etc/php/7.2/fpm/php-fpm.conf
  notify:
    - restart php7.2-fpm
