- name: install
  apt:
    name: git

- name: copy .gitconfig file for user root
  template:
    src: gitconfig.j2
    dest: /root/.gitconfig
    owner: root
    group: root
    mode: 0600

- name: copy .gitconfig file for user vagrant
  template:
    src: gitconfig.j2
    dest: /home/vagrant/.gitconfig
    owner: vagrant
    group: vagrant
    mode: 0600
