---
- name: add key
  apt_key: keyserver=keyserver.ubuntu.com id=00A6F0A3C300EE8C state=present

- name: app repository
  apt_repository: repo='deb http://ppa.launchpad.net/nginx/stable/ubuntu xenial main' state=present

- name: app src repository
  apt_repository: repo='deb-src http://ppa.launchpad.net/nginx/stable/ubuntu xenial main' state=present

- name: install
  apt: name={{ item }} state=present
  with_items:
    - nginx-light

- name: force nginx start, if installed
  service: name=nginx state=started enabled=true

- name: generate certificate for {{ hostname }}
  command: "{{ role_path }}/files/openssl.sh {{ hostname }}"
  notify:
    - restart nginx

- name: generate certificate for {{ item.subhostname }}.{{ hostname }}
  command: "{{ role_path }}/files/openssl.sh {{ hostname }} {{ item.subhostname }}"
  with_items: "{{ subhosts }}"
  notify:
    - restart nginx

- name: nginx.conf
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: cors.conf
  template:
    src=cors.conf.j2
    dest=/etc/nginx/cors.conf
  notify:
    - restart nginx
