- name: install
  apt:
    name: nginx-light

- name: generate certificate for {{ item }}
  command: openssl req -nodes -x509 -newkey rsa:4096 -keyout /etc/nginx/{{ item }}.key -out /etc/nginx/{{ item }}.crt -days 365 -subj "/C=CH/ST=Zurich/L=Zurich/CN={{ item }}"
  args:
    creates: /etc/nginx/{{ item }}.crt
  with_items: "{{ nginx.certificates }}"

- name: nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  register: configuration

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  when: configuration.changed
