---
- hosts: all
  become: true
  roles:
    - general
    - { role: bash, when: general.config.shell == 'bash' }
    - { role: elasticsearch-5, when: role.elasticsearch and elasticsearch.version == 5}
    - { role: freetds, when: role.freetds }
    - git
    - { role: mariadb-10.0-original, when: role.mariadb and mariadb.version == '10.0-original' }
    - { role: mariadb-10.0, when: role.mariadb and mariadb.version == 10.0 }
    - { role: mariadb-10.1, when: role.mariadb and mariadb.version == 10.1 }
    - { role: mariadb-10.2, when: role.mariadb and mariadb.version == 10.2 }
    - { role: nginx-application-bolt2, when: "'bolt2' in applications" }
    - { role: nginx-application-bolt3, when: "'bolt3' in applications" }
    - { role: nginx-application-contao3, when: "'contao3' in applications" }
    - { role: nginx-application-drupal7, when: "'drupal7' in applications" }
    - { role: nginx-application-drupal8, when: "'drupal8' in applications" }
    - { role: nginx-application-lavarel5, when: "'lavarel5' in applications" }
    - { role: nginx-application-magento1, when: "'magento1' in applications" }
    - { role: nginx-application-shopware, when: "'shopware' in applications" }
    - { role: nginx-application-slim3, when: "'slim3' in applications" }
    - { role: nginx-application-symfony1, when: "'symfony1' in applications" }
    - { role: nginx-application-symfony2, when: "'symfony2' in applications" }
    - { role: nginx-application-symfony3, when: "'symfony3' in applications" }
    - { role: nginx-application-wordpress4, when: "'wordpress4' in applications" }
    - nginx
    - { role: nodejs-4-original, when: role.nodejs and nodejs.version == '4-original' }
    - { role: nodejs-4, when: role.nodejs and nodejs.version == 4 }
    - { role: nodejs-5, when: role.nodejs and nodejs.version == 5 }
    - { role: nodejs-6, when: role.nodejs and nodejs.version == 6 }
    - { role: nodejs-7, when: role.nodejs and nodejs.version == 7 }
    - { role: nodejs-8, when: role.nodejs and nodejs.version == 8 }
    - { role: php-7.0-original, when: php.version == '7.0-original' }
    - { role: php-7.0, when: php.version == 7.0 }
    - { role: php-7.1, when: php.version == 7.1 }
    - php-tools
    - php-application
    - { role: php-application-drupal7, when: "'drupal7' in applications" }
    - { role: php-application-drupal8, when: "'drupal8' in applications" }
    - { role: php-application-slim3, when: "'slim3' in applications" }
    - { role: php-application-symfony2, when: "'symfony2' in applications" }
    - { role: php-application-symfony3, when: "'symfony3' in applications" }
    - { role: php-application-wordpress4, when: "'wordpress4' in applications" }
    - { role: zsh, when: general.config.shell == 'zsh' }
    - cleanup
