- name: add apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  when: postgresql.version != '10-original'

- name: add repository
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main'
  when: postgresql.version != '10-original'

- name: install
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - "postgresql-{{ postgresql.version|replace('-original', '') }}"
      - python-psycopg2
      - libpq-dev
  register: installed

- name: install | wait for postgresql
  wait_for:
    port: 5432
  when: installed.changed

- name: configure postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ postgresql.version|replace('-original', '') }}/main/postgresql.conf"
  register: configuration

- name: restart postgresql
  systemd:
    name: postgresql
    state: restarted
  when: configuration.changed

- name: wait for postgresql
  wait_for:
    port: "{{ postgresql.config.port }}"
  when: configuration.changed

- name: change default user to {{ postgresql.username }} / {{ postgresql.password }}
  postgresql_user:
    name: "{{ postgresql.username }}"
    password: "{{ postgresql.password }}"
    role_attr_flags: SUPERUSER
    port: "{{ postgresql.config.port }}"
  become_user: postgres
  when: postgresql.password != ''

- name: change default user to {{ postgresql.username }}
  postgresql_user:
    name: "{{ postgresql.username }}"
    role_attr_flags: SUPERUSER
    port: "{{ postgresql.config.port }}"
  become_user: postgres
  when: postgresql.password == ''

- name: copy .pgpass for postgres
  template:
    src: user-pgpass.j2
    dest: /var/lib/postgresql/.pgpass
    owner: postgres
    group: postgres
    mode: 0600
